const COMMANDS: &[&str] = &[
    "copy_uri_to_path",
    "save_image_to_gallery",
    "use_background_audio",
    "set_system_ui_visibility",
    "get_status_bar_height",
    "get_sys_fonts_list",
    "intercept_keys",
    "lock_screen_orientation",
    "get_system_color_scheme",
    "get_safe_area_insets",
    "get_screen_brightness",
    "set_screen_brightness",
    "get_external_sdcard_path",
    "show_lookup_popover",
    "get_lookup_dictionary",
    "clear_lookup_dictionary",
    "select_directory",
    "register_listener",
    "remove_listener",
    "request_manage_storage_permission",
    "check_permissions",
    "request_permissions",
    "checkPermissions",
    "requestPermissions",
    "set_secure_item",
    "get_secure_item",
    "clear_secure_item",
    "refresh_eink_screen",
    "update_reading_widget",
    "capture_webview_region",
    "set_text_selection_suppressed",
];

fn main() {
    tauri_plugin::Builder::new(COMMANDS)
        .android_path("android")
        .ios_path("ios")
        .build();
}
