import { existsSync, readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { describe, expect, test } from 'vitest';

const projectPath = (path: string) => resolve(process.cwd(), path);
const readSource = (path: string) => readFileSync(projectPath(path), 'utf8');

describe('local TTS engine contract', () => {
  test('retains only native and browser speech engines', () => {
    const controller = readSource('src/services/tts/TTSController.ts');
    const exports = readSource('src/services/tts/index.ts');
    const pronouncer = readSource('src/services/tts/wordPronouncer.ts');

    for (const source of [controller, exports, pronouncer]) {
      expect(source).not.toMatch(/EdgeTTS|edgeTTS|BufferedTTS|TTSDownloader/);
    }
    expect(controller).toContain('WebSpeechClient');
    expect(controller).toContain('NativeTTSClient');
    expect(exports).toContain("export * from './WebSpeechClient'");
    expect(exports).toContain("export * from './NativeTTSClient'");
  });

  test('does not retain online synthesis, download, or persistent audio-cache modules', () => {
    for (const path of [
      'src/libs/edgeTTS.ts',
      'src/services/tts/EdgeTTSClient.ts',
      'src/services/tts/BufferedTTSClient.ts',
      'src/services/tts/NativeAudioPlayer.ts',
      'src/services/tts/TTSAudioPlayer.ts',
      'src/services/tts/WebAudioPlayer.ts',
      'src/services/tts/TTSDownloader.ts',
      'src/services/tts/downloadChapters.ts',
      'src/services/tts/providers',
      'src/app/reader/hooks/useTTSDownloads.ts',
      'src/app/reader/components/tts/TTSChaptersView.tsx',
      'src/app/reader/components/tts/DownloadBadge.tsx',
    ]) {
      expect(existsSync(projectPath(path)), `${path} should be removed`).toBe(false);
    }
  });

  test('keeps the ordinary reading, timeline, highlighting, and media-session chain', () => {
    for (const path of [
      'src/services/tts/WebSpeechClient.ts',
      'src/services/tts/NativeTTSClient.ts',
      'src/services/tts/TTSController.ts',
      'src/services/tts/SectionTimeline.ts',
      'src/services/tts/wordHighlight.ts',
      'src/services/tts/ttsMediaBridge.ts',
      'src/services/tts/audioKeepAlive.ts',
    ]) {
      expect(existsSync(projectPath(path)), `${path} should remain`).toBe(true);
    }
  });

  test('keeps only lightweight Web Audio helpers required by local native playback', () => {
    const source = readSource('src/services/tts/audioKeepAlive.ts');

    expect(source).not.toMatch(/export class WebAudioPlayer|scheduleChunk|decodeAudioData/);
    expect(source).toContain('ensureSharedAudioContext');
    expect(source).toContain('startAudioKeepAlive');
    expect(source).toContain('stopAudioKeepAlive');
  });

  test('does not expose the retired native playout or preload compatibility API', () => {
    for (const path of [
      'src/services/tts/NativeTTSClient.ts',
      'src-tauri/plugins/tauri-plugin-native-tts/build.rs',
      'src-tauri/plugins/tauri-plugin-native-tts/src/commands.rs',
      'src-tauri/plugins/tauri-plugin-native-tts/src/desktop.rs',
      'src-tauri/plugins/tauri-plugin-native-tts/src/lib.rs',
      'src-tauri/plugins/tauri-plugin-native-tts/src/mobile.rs',
      'src-tauri/plugins/tauri-plugin-native-tts/src/models.rs',
      'src-tauri/plugins/tauri-plugin-native-tts/android/src/main/java/NativeTTSPlugin.kt',
      'src-tauri/plugins/tauri-plugin-native-tts/ios/Sources/NativeTTSPlugin.swift',
      'src-tauri/plugins/tauri-plugin-native-tts/permissions/default.toml',
      'src-tauri/plugins/tauri-plugin-native-tts/permissions/autogenerated/reference.md',
      'src-tauri/plugins/tauri-plugin-native-tts/permissions/schemas/schema.json',
    ]) {
      expect(readSource(path), path).not.toMatch(
        /\bpreload\b|playout_(?:enqueue|control|position)|allow-playout-(?:enqueue|control|position)/i,
      );
    }

    for (const path of [
      'src-tauri/plugins/tauri-plugin-native-tts/permissions/autogenerated/commands/playout_enqueue.toml',
      'src-tauri/plugins/tauri-plugin-native-tts/permissions/autogenerated/commands/playout_control.toml',
      'src-tauri/plugins/tauri-plugin-native-tts/permissions/autogenerated/commands/playout_position.toml',
    ]) {
      expect(existsSync(projectPath(path)), `${path} should be removed`).toBe(false);
    }
  });
});
